name: Docker Image CI

on: 
  push:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dcr.teletraan.io/library/hook-proxy:latest
    - name: Login docker regsitry
      run: docker login dcr.teletraan.io -u ${{ secrets.DCR_USER }} -p ${{ secrets.DCR_PASSWORD }}
    - name: Push the Docker image
      run: docker push dcr.teletraan.io/library/hook-proxy:latest
